//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Demos/FunctionDev/LDtkDemo/demo_ldtk_ldtkProject.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_ldtk_enum
{
    /// <summary>
    /// LDtk Enum for demo_ldtk_ldtkEnum
    /// </summary>
    public enum CameraMode
    {
        Fixed,
        Follow
    }
}