//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/GameMain/LDtkProject/gm_ldtk_project.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain.LDtk
{
    /// <summary>
    /// LDtk Enum for GmLDtkEnums
    /// </summary>
    public enum CameraMode
    {
        Fixed,
        Follow
    }
}